package com.base.utils.cxfclient.postapi.namespace;

import com.base.utils.cxfclient.CXFClientRequestVO;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-25T09:35:39.474+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://namespace.postApi/", name = "PostApiService")
@XmlSeeAlso({ObjectFactory.class})
public interface PostApiService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "postApi", targetNamespace = "http://namespace.postApi/", className = "com.base.utils.cxfclient.postapi.namespace.PostApi")
    @WebMethod
    @ResponseWrapper(localName = "postApiResponse", targetNamespace = "http://namespace.postApi/", className = "com.base.utils.cxfclient.postapi.namespace.PostApiResponse")
    public String postApi(
            @WebParam(name = "CXFClientRequestVO", targetNamespace = "")
            CXFClientRequestVO cxfClientRequestVO
    );
}
