package com.base.database.publicd.mapper;

import com.base.database.publicd.model.PublicItemInventory;
import com.base.database.publicd.model.PublicItemInventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicItemInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int countByExample(PublicItemInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int deleteByExample(PublicItemInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int insert(PublicItemInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int insertSelective(PublicItemInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    List<PublicItemInventory> selectByExample(PublicItemInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    PublicItemInventory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PublicItemInventory record, @Param("example") PublicItemInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PublicItemInventory record, @Param("example") PublicItemInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicItemInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_item_inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicItemInventory record);
}