package com.base.database.publicd.mapper;

import com.base.database.publicd.model.PublicDataDict;
import com.base.database.publicd.model.PublicDataDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicDataDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int countByExample(PublicDataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int deleteByExample(PublicDataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int insert(PublicDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int insertSelective(PublicDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    List<PublicDataDict> selectByExample(PublicDataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    PublicDataDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PublicDataDict record, @Param("example") PublicDataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PublicDataDict record, @Param("example") PublicDataDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicDataDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_data_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicDataDict record);
}