package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerRole;
import com.base.database.userinfo.model.UsercontrollerRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int insert(UsercontrollerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    List<UsercontrollerRole> selectByExample(UsercontrollerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    UsercontrollerRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerRole record, @Param("example") UsercontrollerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerRole record, @Param("example") UsercontrollerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerRole record);
}