package com.base.database.userinfo.mapper;

import com.base.database.userinfo.model.UsercontrollerRolePermission;
import com.base.database.userinfo.model.UsercontrollerRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercontrollerRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int countByExample(UsercontrollerRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int deleteByExample(UsercontrollerRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int insert(UsercontrollerRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(UsercontrollerRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    List<UsercontrollerRolePermission> selectByExample(UsercontrollerRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    UsercontrollerRolePermission selectByPrimaryKey(Integer rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsercontrollerRolePermission record, @Param("example") UsercontrollerRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsercontrollerRolePermission record, @Param("example") UsercontrollerRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsercontrollerRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercontroller_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsercontrollerRolePermission record);
}