package com.base.database.userinfo.model;

public class PublicDataDictCategorySpecifics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_id
     *
     * @mbggenerated
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_en_name
     *
     * @mbggenerated
     */
    private String itemEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_ch_name
     *
     * @mbggenerated
     */
    private String itemChName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_level
     *
     * @mbggenerated
     */
    private String itemLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_parent_id
     *
     * @mbggenerated
     */
    private String itemParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.item_type
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_data_dict_categoryspecifics.site_id
     *
     * @mbggenerated
     */
    private String siteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.id
     *
     * @return the value of public_data_dict_categoryspecifics.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.id
     *
     * @param id the value for public_data_dict_categoryspecifics.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.uuid
     *
     * @return the value of public_data_dict_categoryspecifics.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.uuid
     *
     * @param uuid the value for public_data_dict_categoryspecifics.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_id
     *
     * @return the value of public_data_dict_categoryspecifics.item_id
     *
     * @mbggenerated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_id
     *
     * @param itemId the value for public_data_dict_categoryspecifics.item_id
     *
     * @mbggenerated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_en_name
     *
     * @return the value of public_data_dict_categoryspecifics.item_en_name
     *
     * @mbggenerated
     */
    public String getItemEnName() {
        return itemEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_en_name
     *
     * @param itemEnName the value for public_data_dict_categoryspecifics.item_en_name
     *
     * @mbggenerated
     */
    public void setItemEnName(String itemEnName) {
        this.itemEnName = itemEnName == null ? null : itemEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_ch_name
     *
     * @return the value of public_data_dict_categoryspecifics.item_ch_name
     *
     * @mbggenerated
     */
    public String getItemChName() {
        return itemChName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_ch_name
     *
     * @param itemChName the value for public_data_dict_categoryspecifics.item_ch_name
     *
     * @mbggenerated
     */
    public void setItemChName(String itemChName) {
        this.itemChName = itemChName == null ? null : itemChName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_level
     *
     * @return the value of public_data_dict_categoryspecifics.item_level
     *
     * @mbggenerated
     */
    public String getItemLevel() {
        return itemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_level
     *
     * @param itemLevel the value for public_data_dict_categoryspecifics.item_level
     *
     * @mbggenerated
     */
    public void setItemLevel(String itemLevel) {
        this.itemLevel = itemLevel == null ? null : itemLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_parent_id
     *
     * @return the value of public_data_dict_categoryspecifics.item_parent_id
     *
     * @mbggenerated
     */
    public String getItemParentId() {
        return itemParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_parent_id
     *
     * @param itemParentId the value for public_data_dict_categoryspecifics.item_parent_id
     *
     * @mbggenerated
     */
    public void setItemParentId(String itemParentId) {
        this.itemParentId = itemParentId == null ? null : itemParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.item_type
     *
     * @return the value of public_data_dict_categoryspecifics.item_type
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.item_type
     *
     * @param itemType the value for public_data_dict_categoryspecifics.item_type
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_data_dict_categoryspecifics.site_id
     *
     * @return the value of public_data_dict_categoryspecifics.site_id
     *
     * @mbggenerated
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_data_dict_categoryspecifics.site_id
     *
     * @param siteId the value for public_data_dict_categoryspecifics.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }
}