package com.base.database.userinfo.model;

public class UsercontrollerRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    private Integer rolePermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_role_permission.permission_id
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercontroller_role_permission.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_role_permission.role_permission_id
     *
     * @return the value of usercontroller_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    public Integer getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_role_permission.role_permission_id
     *
     * @param rolePermissionId the value for usercontroller_role_permission.role_permission_id
     *
     * @mbggenerated
     */
    public void setRolePermissionId(Integer rolePermissionId) {
        this.rolePermissionId = rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_role_permission.permission_id
     *
     * @return the value of usercontroller_role_permission.permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_role_permission.permission_id
     *
     * @param permissionId the value for usercontroller_role_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercontroller_role_permission.role_id
     *
     * @return the value of usercontroller_role_permission.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercontroller_role_permission.role_id
     *
     * @param roleId the value for usercontroller_role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}