package com.base.database.trading.mapper;

import com.base.database.trading.model.AutoAssessDetail;
import com.base.database.trading.model.AutoAssessDetailExample;
import com.base.database.trading.model.AutoAssessDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoAssessDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int countByExample(AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int deleteByExample(AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int insert(AutoAssessDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int insertSelective(AutoAssessDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    List<AutoAssessDetailWithBLOBs> selectByExampleWithBLOBs(AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    List<AutoAssessDetail> selectByExample(AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    AutoAssessDetailWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AutoAssessDetailWithBLOBs record, @Param("example") AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") AutoAssessDetailWithBLOBs record, @Param("example") AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AutoAssessDetail record, @Param("example") AutoAssessDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutoAssessDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AutoAssessDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_assess_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutoAssessDetail record);
}