package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingGetEBPCaseDetail;
import com.base.database.trading.model.TradingGetEBPCaseDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingGetEBPCaseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int countByExample(TradingGetEBPCaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TradingGetEBPCaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int insert(TradingGetEBPCaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int insertSelective(TradingGetEBPCaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    List<TradingGetEBPCaseDetail> selectByExample(TradingGetEBPCaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    TradingGetEBPCaseDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingGetEBPCaseDetail record, @Param("example") TradingGetEBPCaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingGetEBPCaseDetail record, @Param("example") TradingGetEBPCaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingGetEBPCaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_ebpcase_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingGetEBPCaseDetail record);
}