package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingCaseResponseHistory;
import com.base.database.trading.model.TradingCaseResponseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingCaseResponseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int countByExample(TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int deleteByExample(TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int insert(TradingCaseResponseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int insertSelective(TradingCaseResponseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    List<TradingCaseResponseHistory> selectByExampleWithBLOBs(TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    List<TradingCaseResponseHistory> selectByExample(TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    TradingCaseResponseHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingCaseResponseHistory record, @Param("example") TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingCaseResponseHistory record, @Param("example") TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingCaseResponseHistory record, @Param("example") TradingCaseResponseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingCaseResponseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingCaseResponseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_case_response_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingCaseResponseHistory record);
}