package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingShippingservicecostoverride;
import com.base.database.trading.model.TradingShippingservicecostoverrideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingShippingservicecostoverrideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int countByExample(TradingShippingservicecostoverrideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int deleteByExample(TradingShippingservicecostoverrideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int insert(TradingShippingservicecostoverride record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int insertSelective(TradingShippingservicecostoverride record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    List<TradingShippingservicecostoverride> selectByExample(TradingShippingservicecostoverrideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    TradingShippingservicecostoverride selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingShippingservicecostoverride record, @Param("example") TradingShippingservicecostoverrideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingShippingservicecostoverride record, @Param("example") TradingShippingservicecostoverrideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingShippingservicecostoverride record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingservicecostoverride
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingShippingservicecostoverride record);
}