package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingShippingserviceoptions;
import com.base.database.trading.model.TradingShippingserviceoptionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingShippingserviceoptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int countByExample(TradingShippingserviceoptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int deleteByExample(TradingShippingserviceoptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int insert(TradingShippingserviceoptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int insertSelective(TradingShippingserviceoptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    List<TradingShippingserviceoptions> selectByExample(TradingShippingserviceoptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    TradingShippingserviceoptions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingShippingserviceoptions record, @Param("example") TradingShippingserviceoptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingShippingserviceoptions record, @Param("example") TradingShippingserviceoptionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingShippingserviceoptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingserviceoptions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingShippingserviceoptions record);
}