package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingOrderGetItem;
import com.base.database.trading.model.TradingOrderGetItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingOrderGetItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int countByExample(TradingOrderGetItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int deleteByExample(TradingOrderGetItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int insert(TradingOrderGetItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int insertSelective(TradingOrderGetItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    List<TradingOrderGetItem> selectByExample(TradingOrderGetItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    TradingOrderGetItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingOrderGetItem record, @Param("example") TradingOrderGetItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingOrderGetItem record, @Param("example") TradingOrderGetItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingOrderGetItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingOrderGetItem record);
}