package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingTemplateInitTable;
import com.base.database.trading.model.TradingTemplateInitTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingTemplateInitTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int countByExample(TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int deleteByExample(TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int insert(TradingTemplateInitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int insertSelective(TradingTemplateInitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    List<TradingTemplateInitTable> selectByExampleWithBLOBs(TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    List<TradingTemplateInitTable> selectByExample(TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    TradingTemplateInitTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingTemplateInitTable record, @Param("example") TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingTemplateInitTable record, @Param("example") TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingTemplateInitTable record, @Param("example") TradingTemplateInitTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingTemplateInitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingTemplateInitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_template_init_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingTemplateInitTable record);
}