package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingOrderGetSellerTransactions;
import com.base.database.trading.model.TradingOrderGetSellerTransactionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingOrderGetSellerTransactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int countByExample(TradingOrderGetSellerTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int deleteByExample(TradingOrderGetSellerTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int insert(TradingOrderGetSellerTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int insertSelective(TradingOrderGetSellerTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    List<TradingOrderGetSellerTransactions> selectByExample(TradingOrderGetSellerTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    TradingOrderGetSellerTransactions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingOrderGetSellerTransactions record, @Param("example") TradingOrderGetSellerTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingOrderGetSellerTransactions record, @Param("example") TradingOrderGetSellerTransactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingOrderGetSellerTransactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_order_get_seller_transactions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingOrderGetSellerTransactions record);
}