package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingFeedBackDetail;
import com.base.database.trading.model.TradingFeedBackDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingFeedBackDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int countByExample(TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int deleteByExample(TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int insert(TradingFeedBackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int insertSelective(TradingFeedBackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    List<TradingFeedBackDetail> selectByExampleWithBLOBs(TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    List<TradingFeedBackDetail> selectByExample(TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    TradingFeedBackDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingFeedBackDetail record, @Param("example") TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingFeedBackDetail record, @Param("example") TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingFeedBackDetail record, @Param("example") TradingFeedBackDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingFeedBackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingFeedBackDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_feedbackdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingFeedBackDetail record);
}