package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingListingData;
import com.base.database.trading.model.TradingListingDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingListingDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int countByExample(TradingListingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int deleteByExample(TradingListingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int insert(TradingListingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int insertSelective(TradingListingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    List<TradingListingData> selectByExample(TradingListingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    TradingListingData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingListingData record, @Param("example") TradingListingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingListingData record, @Param("example") TradingListingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingListingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_listing_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingListingData record);
}