package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingAttrMores;
import com.base.database.trading.model.TradingAttrMoresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingAttrMoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int countByExample(TradingAttrMoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int deleteByExample(TradingAttrMoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int insert(TradingAttrMores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int insertSelective(TradingAttrMores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    List<TradingAttrMores> selectByExample(TradingAttrMoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    TradingAttrMores selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingAttrMores record, @Param("example") TradingAttrMoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingAttrMores record, @Param("example") TradingAttrMoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingAttrMores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_attr_mores
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingAttrMores record);
}