package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingGetDisputeMessage;
import com.base.database.trading.model.TradingGetDisputeMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingGetDisputeMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int countByExample(TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int deleteByExample(TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int insert(TradingGetDisputeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int insertSelective(TradingGetDisputeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    List<TradingGetDisputeMessage> selectByExampleWithBLOBs(TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    List<TradingGetDisputeMessage> selectByExample(TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    TradingGetDisputeMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingGetDisputeMessage record, @Param("example") TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingGetDisputeMessage record, @Param("example") TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingGetDisputeMessage record, @Param("example") TradingGetDisputeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingGetDisputeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingGetDisputeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_get_dispute_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingGetDisputeMessage record);
}