package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingInternationalshippingserviceoptionDoc;
import com.base.database.trading.model.TradingInternationalshippingserviceoptionDocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingInternationalshippingserviceoptionDocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int countByExample(TradingInternationalshippingserviceoptionDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int deleteByExample(TradingInternationalshippingserviceoptionDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int insert(TradingInternationalshippingserviceoptionDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int insertSelective(TradingInternationalshippingserviceoptionDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    List<TradingInternationalshippingserviceoptionDoc> selectByExample(TradingInternationalshippingserviceoptionDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    TradingInternationalshippingserviceoptionDoc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingInternationalshippingserviceoptionDoc record, @Param("example") TradingInternationalshippingserviceoptionDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingInternationalshippingserviceoptionDoc record, @Param("example") TradingInternationalshippingserviceoptionDocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingInternationalshippingserviceoptionDoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_internationalshippingserviceoption_doc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingInternationalshippingserviceoptionDoc record);
}