package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingItem;
import com.base.database.trading.model.TradingItemExample;
import com.base.database.trading.model.TradingItemWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int countByExample(TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int deleteByExample(TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int insert(TradingItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int insertSelective(TradingItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    List<TradingItemWithBLOBs> selectByExampleWithBLOBs(TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    List<TradingItem> selectByExample(TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    TradingItemWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingItemWithBLOBs record, @Param("example") TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingItemWithBLOBs record, @Param("example") TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingItem record, @Param("example") TradingItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingItemWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingItem record);
}