package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingPicturedetails;
import com.base.database.trading.model.TradingPicturedetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingPicturedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int countByExample(TradingPicturedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int deleteByExample(TradingPicturedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int insert(TradingPicturedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int insertSelective(TradingPicturedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    List<TradingPicturedetails> selectByExample(TradingPicturedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    TradingPicturedetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingPicturedetails record, @Param("example") TradingPicturedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingPicturedetails record, @Param("example") TradingPicturedetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingPicturedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_picturedetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingPicturedetails record);
}