package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingReturnpolicy;
import com.base.database.trading.model.TradingReturnpolicyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingReturnpolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int countByExample(TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int deleteByExample(TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int insert(TradingReturnpolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int insertSelective(TradingReturnpolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    List<TradingReturnpolicy> selectByExampleWithBLOBs(TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    List<TradingReturnpolicy> selectByExample(TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    TradingReturnpolicy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingReturnpolicy record, @Param("example") TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TradingReturnpolicy record, @Param("example") TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingReturnpolicy record, @Param("example") TradingReturnpolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingReturnpolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradingReturnpolicy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_returnpolicy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingReturnpolicy record);
}