package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingProgress;
import com.base.database.trading.model.TradingProgressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int countByExample(TradingProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int deleteByExample(TradingProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int insert(TradingProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int insertSelective(TradingProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    List<TradingProgress> selectByExample(TradingProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    TradingProgress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingProgress record, @Param("example") TradingProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingProgress record, @Param("example") TradingProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_progress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingProgress record);
}