package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingPriceTrackingPricingRule;
import com.base.database.trading.model.TradingPriceTrackingPricingRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingPriceTrackingPricingRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int countByExample(TradingPriceTrackingPricingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int deleteByExample(TradingPriceTrackingPricingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int insert(TradingPriceTrackingPricingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int insertSelective(TradingPriceTrackingPricingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    List<TradingPriceTrackingPricingRule> selectByExample(TradingPriceTrackingPricingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    TradingPriceTrackingPricingRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingPriceTrackingPricingRule record, @Param("example") TradingPriceTrackingPricingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingPriceTrackingPricingRule record, @Param("example") TradingPriceTrackingPricingRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingPriceTrackingPricingRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_price_tracking_pricing_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingPriceTrackingPricingRule record);
}