package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingInventoryComplementMore;
import com.base.database.trading.model.TradingInventoryComplementMoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingInventoryComplementMoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int countByExample(TradingInventoryComplementMoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int deleteByExample(TradingInventoryComplementMoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int insert(TradingInventoryComplementMore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int insertSelective(TradingInventoryComplementMore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    List<TradingInventoryComplementMore> selectByExample(TradingInventoryComplementMoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    TradingInventoryComplementMore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingInventoryComplementMore record, @Param("example") TradingInventoryComplementMoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingInventoryComplementMore record, @Param("example") TradingInventoryComplementMoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingInventoryComplementMore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_inventory_complement_more
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingInventoryComplementMore record);
}