package com.base.database.trading.mapper;

import com.base.database.trading.model.TradingBuyerRequirementDetails;
import com.base.database.trading.model.TradingBuyerRequirementDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradingBuyerRequirementDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int countByExample(TradingBuyerRequirementDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int deleteByExample(TradingBuyerRequirementDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int insert(TradingBuyerRequirementDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int insertSelective(TradingBuyerRequirementDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    List<TradingBuyerRequirementDetails> selectByExample(TradingBuyerRequirementDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    TradingBuyerRequirementDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradingBuyerRequirementDetails record, @Param("example") TradingBuyerRequirementDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradingBuyerRequirementDetails record, @Param("example") TradingBuyerRequirementDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradingBuyerRequirementDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_buyer_requirement_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradingBuyerRequirementDetails record);
}