package com.base.database.sitemessage.mapper;

import com.base.database.sitemessage.model.PublicSitemessage;
import com.base.database.sitemessage.model.PublicSitemessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicSitemessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int countByExample(PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int deleteByExample(PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int insert(PublicSitemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int insertSelective(PublicSitemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    List<PublicSitemessage> selectByExampleWithBLOBs(PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    List<PublicSitemessage> selectByExample(PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    PublicSitemessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PublicSitemessage record, @Param("example") PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PublicSitemessage record, @Param("example") PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PublicSitemessage record, @Param("example") PublicSitemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicSitemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PublicSitemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_sitemessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicSitemessage record);
}