package com.base.database.task.mapper;

import com.base.database.task.model.ListingDataTask;
import com.base.database.task.model.ListingDataTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ListingDataTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int countByExample(ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int deleteByExample(ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int insert(ListingDataTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int insertSelective(ListingDataTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    List<ListingDataTask> selectByExampleWithBLOBs(ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    List<ListingDataTask> selectByExample(ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    ListingDataTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ListingDataTask record, @Param("example") ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ListingDataTask record, @Param("example") ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ListingDataTask record, @Param("example") ListingDataTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ListingDataTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ListingDataTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listing_data_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ListingDataTask record);
}