package com.base.database.task.mapper;

import com.base.database.task.model.TaskComplement;
import com.base.database.task.model.TaskComplementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskComplementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int countByExample(TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int deleteByExample(TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int insert(TaskComplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int insertSelective(TaskComplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    List<TaskComplement> selectByExampleWithBLOBs(TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    List<TaskComplement> selectByExample(TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    TaskComplement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskComplement record, @Param("example") TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TaskComplement record, @Param("example") TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskComplement record, @Param("example") TaskComplementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskComplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TaskComplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_complement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskComplement record);
}