package com.base.database.trading.model;

import java.util.Date;

public class AutoAssessDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.send_userid
     *
     * @mbggenerated
     */
    private String sendUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.send_username
     *
     * @mbggenerated
     */
    private String sendUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.target_userid
     *
     * @mbggenerated
     */
    private String targetUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.item_id
     *
     * @mbggenerated
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.transactionid
     *
     * @mbggenerated
     */
    private String transactionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.source_id
     *
     * @mbggenerated
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_assess_detail.is_flag
     *
     * @mbggenerated
     */
    private String isFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.id
     *
     * @return the value of auto_assess_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.id
     *
     * @param id the value for auto_assess_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.content
     *
     * @return the value of auto_assess_detail.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.content
     *
     * @param content the value for auto_assess_detail.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.send_userid
     *
     * @return the value of auto_assess_detail.send_userid
     *
     * @mbggenerated
     */
    public String getSendUserid() {
        return sendUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.send_userid
     *
     * @param sendUserid the value for auto_assess_detail.send_userid
     *
     * @mbggenerated
     */
    public void setSendUserid(String sendUserid) {
        this.sendUserid = sendUserid == null ? null : sendUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.send_username
     *
     * @return the value of auto_assess_detail.send_username
     *
     * @mbggenerated
     */
    public String getSendUsername() {
        return sendUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.send_username
     *
     * @param sendUsername the value for auto_assess_detail.send_username
     *
     * @mbggenerated
     */
    public void setSendUsername(String sendUsername) {
        this.sendUsername = sendUsername == null ? null : sendUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.target_userid
     *
     * @return the value of auto_assess_detail.target_userid
     *
     * @mbggenerated
     */
    public String getTargetUserid() {
        return targetUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.target_userid
     *
     * @param targetUserid the value for auto_assess_detail.target_userid
     *
     * @mbggenerated
     */
    public void setTargetUserid(String targetUserid) {
        this.targetUserid = targetUserid == null ? null : targetUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.item_id
     *
     * @return the value of auto_assess_detail.item_id
     *
     * @mbggenerated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.item_id
     *
     * @param itemId the value for auto_assess_detail.item_id
     *
     * @mbggenerated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.transactionid
     *
     * @return the value of auto_assess_detail.transactionid
     *
     * @mbggenerated
     */
    public String getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.transactionid
     *
     * @param transactionid the value for auto_assess_detail.transactionid
     *
     * @mbggenerated
     */
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid == null ? null : transactionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.data_type
     *
     * @return the value of auto_assess_detail.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.data_type
     *
     * @param dataType the value for auto_assess_detail.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.source_id
     *
     * @return the value of auto_assess_detail.source_id
     *
     * @mbggenerated
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.source_id
     *
     * @param sourceId the value for auto_assess_detail.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.create_date
     *
     * @return the value of auto_assess_detail.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.create_date
     *
     * @param createDate the value for auto_assess_detail.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_assess_detail.is_flag
     *
     * @return the value of auto_assess_detail.is_flag
     *
     * @mbggenerated
     */
    public String getIsFlag() {
        return isFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_assess_detail.is_flag
     *
     * @param isFlag the value for auto_assess_detail.is_flag
     *
     * @mbggenerated
     */
    public void setIsFlag(String isFlag) {
        this.isFlag = isFlag == null ? null : isFlag.trim();
    }
}