package com.base.database.trading.model;

import java.util.Date;

public class TradingOrderCalculatedShippingRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.originatingPostalCode
     *
     * @mbggenerated
     */
    private String originatingpostalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.packageDepth
     *
     * @mbggenerated
     */
    private Integer packagedepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.packageLength
     *
     * @mbggenerated
     */
    private Integer packagelength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.packageWidth
     *
     * @mbggenerated
     */
    private Integer packagewidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.packagingHandlingCosts
     *
     * @mbggenerated
     */
    private Double packaginghandlingcosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.shippingIrregular
     *
     * @mbggenerated
     */
    private String shippingirregular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.shippingPackage
     *
     * @mbggenerated
     */
    private String shippingpackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.weightMajor
     *
     * @mbggenerated
     */
    private Integer weightmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.weightMinor
     *
     * @mbggenerated
     */
    private Integer weightminor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_calculatedshippingrate.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.id
     *
     * @return the value of trading_order_calculatedshippingrate.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.id
     *
     * @param id the value for trading_order_calculatedshippingrate.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.originatingPostalCode
     *
     * @return the value of trading_order_calculatedshippingrate.originatingPostalCode
     *
     * @mbggenerated
     */
    public String getOriginatingpostalcode() {
        return originatingpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.originatingPostalCode
     *
     * @param originatingpostalcode the value for trading_order_calculatedshippingrate.originatingPostalCode
     *
     * @mbggenerated
     */
    public void setOriginatingpostalcode(String originatingpostalcode) {
        this.originatingpostalcode = originatingpostalcode == null ? null : originatingpostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.packageDepth
     *
     * @return the value of trading_order_calculatedshippingrate.packageDepth
     *
     * @mbggenerated
     */
    public Integer getPackagedepth() {
        return packagedepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.packageDepth
     *
     * @param packagedepth the value for trading_order_calculatedshippingrate.packageDepth
     *
     * @mbggenerated
     */
    public void setPackagedepth(Integer packagedepth) {
        this.packagedepth = packagedepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.packageLength
     *
     * @return the value of trading_order_calculatedshippingrate.packageLength
     *
     * @mbggenerated
     */
    public Integer getPackagelength() {
        return packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.packageLength
     *
     * @param packagelength the value for trading_order_calculatedshippingrate.packageLength
     *
     * @mbggenerated
     */
    public void setPackagelength(Integer packagelength) {
        this.packagelength = packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.packageWidth
     *
     * @return the value of trading_order_calculatedshippingrate.packageWidth
     *
     * @mbggenerated
     */
    public Integer getPackagewidth() {
        return packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.packageWidth
     *
     * @param packagewidth the value for trading_order_calculatedshippingrate.packageWidth
     *
     * @mbggenerated
     */
    public void setPackagewidth(Integer packagewidth) {
        this.packagewidth = packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.packagingHandlingCosts
     *
     * @return the value of trading_order_calculatedshippingrate.packagingHandlingCosts
     *
     * @mbggenerated
     */
    public Double getPackaginghandlingcosts() {
        return packaginghandlingcosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.packagingHandlingCosts
     *
     * @param packaginghandlingcosts the value for trading_order_calculatedshippingrate.packagingHandlingCosts
     *
     * @mbggenerated
     */
    public void setPackaginghandlingcosts(Double packaginghandlingcosts) {
        this.packaginghandlingcosts = packaginghandlingcosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.shippingIrregular
     *
     * @return the value of trading_order_calculatedshippingrate.shippingIrregular
     *
     * @mbggenerated
     */
    public String getShippingirregular() {
        return shippingirregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.shippingIrregular
     *
     * @param shippingirregular the value for trading_order_calculatedshippingrate.shippingIrregular
     *
     * @mbggenerated
     */
    public void setShippingirregular(String shippingirregular) {
        this.shippingirregular = shippingirregular == null ? null : shippingirregular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.shippingPackage
     *
     * @return the value of trading_order_calculatedshippingrate.shippingPackage
     *
     * @mbggenerated
     */
    public String getShippingpackage() {
        return shippingpackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.shippingPackage
     *
     * @param shippingpackage the value for trading_order_calculatedshippingrate.shippingPackage
     *
     * @mbggenerated
     */
    public void setShippingpackage(String shippingpackage) {
        this.shippingpackage = shippingpackage == null ? null : shippingpackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.weightMajor
     *
     * @return the value of trading_order_calculatedshippingrate.weightMajor
     *
     * @mbggenerated
     */
    public Integer getWeightmajor() {
        return weightmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.weightMajor
     *
     * @param weightmajor the value for trading_order_calculatedshippingrate.weightMajor
     *
     * @mbggenerated
     */
    public void setWeightmajor(Integer weightmajor) {
        this.weightmajor = weightmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.weightMinor
     *
     * @return the value of trading_order_calculatedshippingrate.weightMinor
     *
     * @mbggenerated
     */
    public Integer getWeightminor() {
        return weightminor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.weightMinor
     *
     * @param weightminor the value for trading_order_calculatedshippingrate.weightMinor
     *
     * @mbggenerated
     */
    public void setWeightminor(Integer weightminor) {
        this.weightminor = weightminor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.create_user
     *
     * @return the value of trading_order_calculatedshippingrate.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.create_user
     *
     * @param createUser the value for trading_order_calculatedshippingrate.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.create_time
     *
     * @return the value of trading_order_calculatedshippingrate.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.create_time
     *
     * @param createTime the value for trading_order_calculatedshippingrate.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_calculatedshippingrate.uuid
     *
     * @return the value of trading_order_calculatedshippingrate.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_calculatedshippingrate.uuid
     *
     * @param uuid the value for trading_order_calculatedshippingrate.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }
}