package com.base.database.trading.model;

import java.util.Date;

public class TradingShippingpackagedetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.MeasurementUnit
     *
     * @mbggenerated
     */
    private String measurementunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.PackageDepth
     *
     * @mbggenerated
     */
    private Double packagedepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.PackageLength
     *
     * @mbggenerated
     */
    private Double packagelength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.PackageWidth
     *
     * @mbggenerated
     */
    private Double packagewidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.ShippingIrregular
     *
     * @mbggenerated
     */
    private String shippingirregular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.ShippingPackage
     *
     * @mbggenerated
     */
    private String shippingpackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.WeightMajor
     *
     * @mbggenerated
     */
    private Double weightmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.WeightMinor
     *
     * @mbggenerated
     */
    private Double weightminor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_shippingpackagedetails.parent_uuid
     *
     * @mbggenerated
     */
    private String parentUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.id
     *
     * @return the value of trading_shippingpackagedetails.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.id
     *
     * @param id the value for trading_shippingpackagedetails.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.MeasurementUnit
     *
     * @return the value of trading_shippingpackagedetails.MeasurementUnit
     *
     * @mbggenerated
     */
    public String getMeasurementunit() {
        return measurementunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.MeasurementUnit
     *
     * @param measurementunit the value for trading_shippingpackagedetails.MeasurementUnit
     *
     * @mbggenerated
     */
    public void setMeasurementunit(String measurementunit) {
        this.measurementunit = measurementunit == null ? null : measurementunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.PackageDepth
     *
     * @return the value of trading_shippingpackagedetails.PackageDepth
     *
     * @mbggenerated
     */
    public Double getPackagedepth() {
        return packagedepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.PackageDepth
     *
     * @param packagedepth the value for trading_shippingpackagedetails.PackageDepth
     *
     * @mbggenerated
     */
    public void setPackagedepth(Double packagedepth) {
        this.packagedepth = packagedepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.PackageLength
     *
     * @return the value of trading_shippingpackagedetails.PackageLength
     *
     * @mbggenerated
     */
    public Double getPackagelength() {
        return packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.PackageLength
     *
     * @param packagelength the value for trading_shippingpackagedetails.PackageLength
     *
     * @mbggenerated
     */
    public void setPackagelength(Double packagelength) {
        this.packagelength = packagelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.PackageWidth
     *
     * @return the value of trading_shippingpackagedetails.PackageWidth
     *
     * @mbggenerated
     */
    public Double getPackagewidth() {
        return packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.PackageWidth
     *
     * @param packagewidth the value for trading_shippingpackagedetails.PackageWidth
     *
     * @mbggenerated
     */
    public void setPackagewidth(Double packagewidth) {
        this.packagewidth = packagewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.ShippingIrregular
     *
     * @return the value of trading_shippingpackagedetails.ShippingIrregular
     *
     * @mbggenerated
     */
    public String getShippingirregular() {
        return shippingirregular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.ShippingIrregular
     *
     * @param shippingirregular the value for trading_shippingpackagedetails.ShippingIrregular
     *
     * @mbggenerated
     */
    public void setShippingirregular(String shippingirregular) {
        this.shippingirregular = shippingirregular == null ? null : shippingirregular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.ShippingPackage
     *
     * @return the value of trading_shippingpackagedetails.ShippingPackage
     *
     * @mbggenerated
     */
    public String getShippingpackage() {
        return shippingpackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.ShippingPackage
     *
     * @param shippingpackage the value for trading_shippingpackagedetails.ShippingPackage
     *
     * @mbggenerated
     */
    public void setShippingpackage(String shippingpackage) {
        this.shippingpackage = shippingpackage == null ? null : shippingpackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.WeightMajor
     *
     * @return the value of trading_shippingpackagedetails.WeightMajor
     *
     * @mbggenerated
     */
    public Double getWeightmajor() {
        return weightmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.WeightMajor
     *
     * @param weightmajor the value for trading_shippingpackagedetails.WeightMajor
     *
     * @mbggenerated
     */
    public void setWeightmajor(Double weightmajor) {
        this.weightmajor = weightmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.WeightMinor
     *
     * @return the value of trading_shippingpackagedetails.WeightMinor
     *
     * @mbggenerated
     */
    public Double getWeightminor() {
        return weightminor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.WeightMinor
     *
     * @param weightminor the value for trading_shippingpackagedetails.WeightMinor
     *
     * @mbggenerated
     */
    public void setWeightminor(Double weightminor) {
        this.weightminor = weightminor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.create_user
     *
     * @return the value of trading_shippingpackagedetails.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.create_user
     *
     * @param createUser the value for trading_shippingpackagedetails.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.create_time
     *
     * @return the value of trading_shippingpackagedetails.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.create_time
     *
     * @param createTime the value for trading_shippingpackagedetails.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.uuid
     *
     * @return the value of trading_shippingpackagedetails.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.uuid
     *
     * @param uuid the value for trading_shippingpackagedetails.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.parent_id
     *
     * @return the value of trading_shippingpackagedetails.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.parent_id
     *
     * @param parentId the value for trading_shippingpackagedetails.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_shippingpackagedetails.parent_uuid
     *
     * @return the value of trading_shippingpackagedetails.parent_uuid
     *
     * @mbggenerated
     */
    public String getParentUuid() {
        return parentUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_shippingpackagedetails.parent_uuid
     *
     * @param parentUuid the value for trading_shippingpackagedetails.parent_uuid
     *
     * @mbggenerated
     */
    public void setParentUuid(String parentUuid) {
        this.parentUuid = parentUuid == null ? null : parentUuid.trim();
    }
}