package com.base.database.trading.model;

public class TradingInventoryComplementMore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_inventory_complement_more.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_inventory_complement_more.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_inventory_complement_more.sku_value
     *
     * @mbggenerated
     */
    private String skuValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_inventory_complement_more.sku_type
     *
     * @mbggenerated
     */
    private String skuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_inventory_complement_more.sku_id
     *
     * @mbggenerated
     */
    private Long skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_inventory_complement_more.id
     *
     * @return the value of trading_inventory_complement_more.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_inventory_complement_more.id
     *
     * @param id the value for trading_inventory_complement_more.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_inventory_complement_more.parent_id
     *
     * @return the value of trading_inventory_complement_more.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_inventory_complement_more.parent_id
     *
     * @param parentId the value for trading_inventory_complement_more.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_inventory_complement_more.sku_value
     *
     * @return the value of trading_inventory_complement_more.sku_value
     *
     * @mbggenerated
     */
    public String getSkuValue() {
        return skuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_inventory_complement_more.sku_value
     *
     * @param skuValue the value for trading_inventory_complement_more.sku_value
     *
     * @mbggenerated
     */
    public void setSkuValue(String skuValue) {
        this.skuValue = skuValue == null ? null : skuValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_inventory_complement_more.sku_type
     *
     * @return the value of trading_inventory_complement_more.sku_type
     *
     * @mbggenerated
     */
    public String getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_inventory_complement_more.sku_type
     *
     * @param skuType the value for trading_inventory_complement_more.sku_type
     *
     * @mbggenerated
     */
    public void setSkuType(String skuType) {
        this.skuType = skuType == null ? null : skuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_inventory_complement_more.sku_id
     *
     * @return the value of trading_inventory_complement_more.sku_id
     *
     * @mbggenerated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_inventory_complement_more.sku_id
     *
     * @param skuId the value for trading_inventory_complement_more.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }
}