package com.base.database.trading.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradingShippingpackagedetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public TradingShippingpackagedetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitIsNull() {
            addCriterion("MeasurementUnit is null");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitIsNotNull() {
            addCriterion("MeasurementUnit is not null");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitEqualTo(String value) {
            addCriterion("MeasurementUnit =", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitNotEqualTo(String value) {
            addCriterion("MeasurementUnit <>", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitGreaterThan(String value) {
            addCriterion("MeasurementUnit >", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitGreaterThanOrEqualTo(String value) {
            addCriterion("MeasurementUnit >=", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitLessThan(String value) {
            addCriterion("MeasurementUnit <", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitLessThanOrEqualTo(String value) {
            addCriterion("MeasurementUnit <=", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitLike(String value) {
            addCriterion("MeasurementUnit like", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitNotLike(String value) {
            addCriterion("MeasurementUnit not like", value, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitIn(List<String> values) {
            addCriterion("MeasurementUnit in", values, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitNotIn(List<String> values) {
            addCriterion("MeasurementUnit not in", values, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitBetween(String value1, String value2) {
            addCriterion("MeasurementUnit between", value1, value2, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andMeasurementunitNotBetween(String value1, String value2) {
            addCriterion("MeasurementUnit not between", value1, value2, "measurementunit");
            return (Criteria) this;
        }

        public Criteria andPackagedepthIsNull() {
            addCriterion("PackageDepth is null");
            return (Criteria) this;
        }

        public Criteria andPackagedepthIsNotNull() {
            addCriterion("PackageDepth is not null");
            return (Criteria) this;
        }

        public Criteria andPackagedepthEqualTo(Double value) {
            addCriterion("PackageDepth =", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthNotEqualTo(Double value) {
            addCriterion("PackageDepth <>", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthGreaterThan(Double value) {
            addCriterion("PackageDepth >", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthGreaterThanOrEqualTo(Double value) {
            addCriterion("PackageDepth >=", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthLessThan(Double value) {
            addCriterion("PackageDepth <", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthLessThanOrEqualTo(Double value) {
            addCriterion("PackageDepth <=", value, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthIn(List<Double> values) {
            addCriterion("PackageDepth in", values, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthNotIn(List<Double> values) {
            addCriterion("PackageDepth not in", values, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthBetween(Double value1, Double value2) {
            addCriterion("PackageDepth between", value1, value2, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagedepthNotBetween(Double value1, Double value2) {
            addCriterion("PackageDepth not between", value1, value2, "packagedepth");
            return (Criteria) this;
        }

        public Criteria andPackagelengthIsNull() {
            addCriterion("PackageLength is null");
            return (Criteria) this;
        }

        public Criteria andPackagelengthIsNotNull() {
            addCriterion("PackageLength is not null");
            return (Criteria) this;
        }

        public Criteria andPackagelengthEqualTo(Double value) {
            addCriterion("PackageLength =", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthNotEqualTo(Double value) {
            addCriterion("PackageLength <>", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthGreaterThan(Double value) {
            addCriterion("PackageLength >", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthGreaterThanOrEqualTo(Double value) {
            addCriterion("PackageLength >=", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthLessThan(Double value) {
            addCriterion("PackageLength <", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthLessThanOrEqualTo(Double value) {
            addCriterion("PackageLength <=", value, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthIn(List<Double> values) {
            addCriterion("PackageLength in", values, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthNotIn(List<Double> values) {
            addCriterion("PackageLength not in", values, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthBetween(Double value1, Double value2) {
            addCriterion("PackageLength between", value1, value2, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagelengthNotBetween(Double value1, Double value2) {
            addCriterion("PackageLength not between", value1, value2, "packagelength");
            return (Criteria) this;
        }

        public Criteria andPackagewidthIsNull() {
            addCriterion("PackageWidth is null");
            return (Criteria) this;
        }

        public Criteria andPackagewidthIsNotNull() {
            addCriterion("PackageWidth is not null");
            return (Criteria) this;
        }

        public Criteria andPackagewidthEqualTo(Double value) {
            addCriterion("PackageWidth =", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthNotEqualTo(Double value) {
            addCriterion("PackageWidth <>", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthGreaterThan(Double value) {
            addCriterion("PackageWidth >", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthGreaterThanOrEqualTo(Double value) {
            addCriterion("PackageWidth >=", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthLessThan(Double value) {
            addCriterion("PackageWidth <", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthLessThanOrEqualTo(Double value) {
            addCriterion("PackageWidth <=", value, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthIn(List<Double> values) {
            addCriterion("PackageWidth in", values, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthNotIn(List<Double> values) {
            addCriterion("PackageWidth not in", values, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthBetween(Double value1, Double value2) {
            addCriterion("PackageWidth between", value1, value2, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andPackagewidthNotBetween(Double value1, Double value2) {
            addCriterion("PackageWidth not between", value1, value2, "packagewidth");
            return (Criteria) this;
        }

        public Criteria andShippingirregularIsNull() {
            addCriterion("ShippingIrregular is null");
            return (Criteria) this;
        }

        public Criteria andShippingirregularIsNotNull() {
            addCriterion("ShippingIrregular is not null");
            return (Criteria) this;
        }

        public Criteria andShippingirregularEqualTo(String value) {
            addCriterion("ShippingIrregular =", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularNotEqualTo(String value) {
            addCriterion("ShippingIrregular <>", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularGreaterThan(String value) {
            addCriterion("ShippingIrregular >", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularGreaterThanOrEqualTo(String value) {
            addCriterion("ShippingIrregular >=", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularLessThan(String value) {
            addCriterion("ShippingIrregular <", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularLessThanOrEqualTo(String value) {
            addCriterion("ShippingIrregular <=", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularLike(String value) {
            addCriterion("ShippingIrregular like", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularNotLike(String value) {
            addCriterion("ShippingIrregular not like", value, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularIn(List<String> values) {
            addCriterion("ShippingIrregular in", values, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularNotIn(List<String> values) {
            addCriterion("ShippingIrregular not in", values, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularBetween(String value1, String value2) {
            addCriterion("ShippingIrregular between", value1, value2, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingirregularNotBetween(String value1, String value2) {
            addCriterion("ShippingIrregular not between", value1, value2, "shippingirregular");
            return (Criteria) this;
        }

        public Criteria andShippingpackageIsNull() {
            addCriterion("ShippingPackage is null");
            return (Criteria) this;
        }

        public Criteria andShippingpackageIsNotNull() {
            addCriterion("ShippingPackage is not null");
            return (Criteria) this;
        }

        public Criteria andShippingpackageEqualTo(String value) {
            addCriterion("ShippingPackage =", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageNotEqualTo(String value) {
            addCriterion("ShippingPackage <>", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageGreaterThan(String value) {
            addCriterion("ShippingPackage >", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageGreaterThanOrEqualTo(String value) {
            addCriterion("ShippingPackage >=", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageLessThan(String value) {
            addCriterion("ShippingPackage <", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageLessThanOrEqualTo(String value) {
            addCriterion("ShippingPackage <=", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageLike(String value) {
            addCriterion("ShippingPackage like", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageNotLike(String value) {
            addCriterion("ShippingPackage not like", value, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageIn(List<String> values) {
            addCriterion("ShippingPackage in", values, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageNotIn(List<String> values) {
            addCriterion("ShippingPackage not in", values, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageBetween(String value1, String value2) {
            addCriterion("ShippingPackage between", value1, value2, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andShippingpackageNotBetween(String value1, String value2) {
            addCriterion("ShippingPackage not between", value1, value2, "shippingpackage");
            return (Criteria) this;
        }

        public Criteria andWeightmajorIsNull() {
            addCriterion("WeightMajor is null");
            return (Criteria) this;
        }

        public Criteria andWeightmajorIsNotNull() {
            addCriterion("WeightMajor is not null");
            return (Criteria) this;
        }

        public Criteria andWeightmajorEqualTo(Double value) {
            addCriterion("WeightMajor =", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorNotEqualTo(Double value) {
            addCriterion("WeightMajor <>", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorGreaterThan(Double value) {
            addCriterion("WeightMajor >", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorGreaterThanOrEqualTo(Double value) {
            addCriterion("WeightMajor >=", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorLessThan(Double value) {
            addCriterion("WeightMajor <", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorLessThanOrEqualTo(Double value) {
            addCriterion("WeightMajor <=", value, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorIn(List<Double> values) {
            addCriterion("WeightMajor in", values, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorNotIn(List<Double> values) {
            addCriterion("WeightMajor not in", values, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorBetween(Double value1, Double value2) {
            addCriterion("WeightMajor between", value1, value2, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightmajorNotBetween(Double value1, Double value2) {
            addCriterion("WeightMajor not between", value1, value2, "weightmajor");
            return (Criteria) this;
        }

        public Criteria andWeightminorIsNull() {
            addCriterion("WeightMinor is null");
            return (Criteria) this;
        }

        public Criteria andWeightminorIsNotNull() {
            addCriterion("WeightMinor is not null");
            return (Criteria) this;
        }

        public Criteria andWeightminorEqualTo(Double value) {
            addCriterion("WeightMinor =", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorNotEqualTo(Double value) {
            addCriterion("WeightMinor <>", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorGreaterThan(Double value) {
            addCriterion("WeightMinor >", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorGreaterThanOrEqualTo(Double value) {
            addCriterion("WeightMinor >=", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorLessThan(Double value) {
            addCriterion("WeightMinor <", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorLessThanOrEqualTo(Double value) {
            addCriterion("WeightMinor <=", value, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorIn(List<Double> values) {
            addCriterion("WeightMinor in", values, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorNotIn(List<Double> values) {
            addCriterion("WeightMinor not in", values, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorBetween(Double value1, Double value2) {
            addCriterion("WeightMinor between", value1, value2, "weightminor");
            return (Criteria) this;
        }

        public Criteria andWeightminorNotBetween(Double value1, Double value2) {
            addCriterion("WeightMinor not between", value1, value2, "weightminor");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Long> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentUuidIsNull() {
            addCriterion("parent_uuid is null");
            return (Criteria) this;
        }

        public Criteria andParentUuidIsNotNull() {
            addCriterion("parent_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andParentUuidEqualTo(String value) {
            addCriterion("parent_uuid =", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidNotEqualTo(String value) {
            addCriterion("parent_uuid <>", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidGreaterThan(String value) {
            addCriterion("parent_uuid >", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidGreaterThanOrEqualTo(String value) {
            addCriterion("parent_uuid >=", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidLessThan(String value) {
            addCriterion("parent_uuid <", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidLessThanOrEqualTo(String value) {
            addCriterion("parent_uuid <=", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidLike(String value) {
            addCriterion("parent_uuid like", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidNotLike(String value) {
            addCriterion("parent_uuid not like", value, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidIn(List<String> values) {
            addCriterion("parent_uuid in", values, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidNotIn(List<String> values) {
            addCriterion("parent_uuid not in", values, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidBetween(String value1, String value2) {
            addCriterion("parent_uuid between", value1, value2, "parentUuid");
            return (Criteria) this;
        }

        public Criteria andParentUuidNotBetween(String value1, String value2) {
            addCriterion("parent_uuid not between", value1, value2, "parentUuid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trading_shippingpackagedetails
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}