package com.base.database.trading.model;

import java.util.Date;

public class TradingOrderAddMemberMessageAAQToPartner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.messagetype
     *
     * @mbggenerated
     */
    private Integer messagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.sender
     *
     * @mbggenerated
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.itemid
     *
     * @mbggenerated
     */
    private String itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.recipientID
     *
     * @mbggenerated
     */
    private String recipientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.messageflag
     *
     * @mbggenerated
     */
    private Integer messageflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.transactionId
     *
     * @mbggenerated
     */
    private String transactionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.replied
     *
     * @mbggenerated
     */
    private String replied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trading_order_addmembermessageaaqtopartner.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.id
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.id
     *
     * @param id the value for trading_order_addmembermessageaaqtopartner.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.messagetype
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.messagetype
     *
     * @mbggenerated
     */
    public Integer getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.messagetype
     *
     * @param messagetype the value for trading_order_addmembermessageaaqtopartner.messagetype
     *
     * @mbggenerated
     */
    public void setMessagetype(Integer messagetype) {
        this.messagetype = messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.subject
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.subject
     *
     * @param subject the value for trading_order_addmembermessageaaqtopartner.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.sender
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.sender
     *
     * @mbggenerated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.sender
     *
     * @param sender the value for trading_order_addmembermessageaaqtopartner.sender
     *
     * @mbggenerated
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.body
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.body
     *
     * @param body the value for trading_order_addmembermessageaaqtopartner.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.itemid
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.itemid
     *
     * @mbggenerated
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.itemid
     *
     * @param itemid the value for trading_order_addmembermessageaaqtopartner.itemid
     *
     * @mbggenerated
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.recipientID
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.recipientID
     *
     * @mbggenerated
     */
    public String getRecipientid() {
        return recipientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.recipientID
     *
     * @param recipientid the value for trading_order_addmembermessageaaqtopartner.recipientID
     *
     * @mbggenerated
     */
    public void setRecipientid(String recipientid) {
        this.recipientid = recipientid == null ? null : recipientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.messageflag
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.messageflag
     *
     * @mbggenerated
     */
    public Integer getMessageflag() {
        return messageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.messageflag
     *
     * @param messageflag the value for trading_order_addmembermessageaaqtopartner.messageflag
     *
     * @mbggenerated
     */
    public void setMessageflag(Integer messageflag) {
        this.messageflag = messageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.transactionId
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.transactionId
     *
     * @mbggenerated
     */
    public String getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.transactionId
     *
     * @param transactionid the value for trading_order_addmembermessageaaqtopartner.transactionId
     *
     * @mbggenerated
     */
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid == null ? null : transactionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.replied
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.replied
     *
     * @mbggenerated
     */
    public String getReplied() {
        return replied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.replied
     *
     * @param replied the value for trading_order_addmembermessageaaqtopartner.replied
     *
     * @mbggenerated
     */
    public void setReplied(String replied) {
        this.replied = replied == null ? null : replied.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.create_user
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.create_user
     *
     * @param createUser the value for trading_order_addmembermessageaaqtopartner.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.create_time
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.create_time
     *
     * @param createTime the value for trading_order_addmembermessageaaqtopartner.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trading_order_addmembermessageaaqtopartner.uuid
     *
     * @return the value of trading_order_addmembermessageaaqtopartner.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trading_order_addmembermessageaaqtopartner.uuid
     *
     * @param uuid the value for trading_order_addmembermessageaaqtopartner.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }
}