package com.base.database.trading.model;

import java.util.Date;

public class TrdingOrderSeller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.aboutMePage
     *
     * @mbggenerated
     */
    private String aboutmepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.feedbackScore
     *
     * @mbggenerated
     */
    private String feedbackscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.positiveFeedbackPercent
     *
     * @mbggenerated
     */
    private Double positivefeedbackpercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.feedbackPrivate
     *
     * @mbggenerated
     */
    private String feedbackprivate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.feedbackRatingStar
     *
     * @mbggenerated
     */
    private String feedbackratingstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.iDVerified
     *
     * @mbggenerated
     */
    private String idverified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.eBayGoodStanding
     *
     * @mbggenerated
     */
    private String ebaygoodstanding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.newUser
     *
     * @mbggenerated
     */
    private String newuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.registrationDate
     *
     * @mbggenerated
     */
    private Date registrationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.site
     *
     * @mbggenerated
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.userID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.userIDChanged
     *
     * @mbggenerated
     */
    private String useridchanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.userIDLastChanged
     *
     * @mbggenerated
     */
    private Date useridlastchanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.vATStatus
     *
     * @mbggenerated
     */
    private String vatstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.sellerInfo_id
     *
     * @mbggenerated
     */
    private Long sellerinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.motorsDealer
     *
     * @mbggenerated
     */
    private String motorsdealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.eBayUnilateralEmail
     *
     * @mbggenerated
     */
    private String ebayunilateralemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trding_order_seller.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.id
     *
     * @return the value of trding_order_seller.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.id
     *
     * @param id the value for trding_order_seller.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.aboutMePage
     *
     * @return the value of trding_order_seller.aboutMePage
     *
     * @mbggenerated
     */
    public String getAboutmepage() {
        return aboutmepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.aboutMePage
     *
     * @param aboutmepage the value for trding_order_seller.aboutMePage
     *
     * @mbggenerated
     */
    public void setAboutmepage(String aboutmepage) {
        this.aboutmepage = aboutmepage == null ? null : aboutmepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.email
     *
     * @return the value of trding_order_seller.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.email
     *
     * @param email the value for trding_order_seller.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.feedbackScore
     *
     * @return the value of trding_order_seller.feedbackScore
     *
     * @mbggenerated
     */
    public String getFeedbackscore() {
        return feedbackscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.feedbackScore
     *
     * @param feedbackscore the value for trding_order_seller.feedbackScore
     *
     * @mbggenerated
     */
    public void setFeedbackscore(String feedbackscore) {
        this.feedbackscore = feedbackscore == null ? null : feedbackscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.positiveFeedbackPercent
     *
     * @return the value of trding_order_seller.positiveFeedbackPercent
     *
     * @mbggenerated
     */
    public Double getPositivefeedbackpercent() {
        return positivefeedbackpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.positiveFeedbackPercent
     *
     * @param positivefeedbackpercent the value for trding_order_seller.positiveFeedbackPercent
     *
     * @mbggenerated
     */
    public void setPositivefeedbackpercent(Double positivefeedbackpercent) {
        this.positivefeedbackpercent = positivefeedbackpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.feedbackPrivate
     *
     * @return the value of trding_order_seller.feedbackPrivate
     *
     * @mbggenerated
     */
    public String getFeedbackprivate() {
        return feedbackprivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.feedbackPrivate
     *
     * @param feedbackprivate the value for trding_order_seller.feedbackPrivate
     *
     * @mbggenerated
     */
    public void setFeedbackprivate(String feedbackprivate) {
        this.feedbackprivate = feedbackprivate == null ? null : feedbackprivate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.feedbackRatingStar
     *
     * @return the value of trding_order_seller.feedbackRatingStar
     *
     * @mbggenerated
     */
    public String getFeedbackratingstar() {
        return feedbackratingstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.feedbackRatingStar
     *
     * @param feedbackratingstar the value for trding_order_seller.feedbackRatingStar
     *
     * @mbggenerated
     */
    public void setFeedbackratingstar(String feedbackratingstar) {
        this.feedbackratingstar = feedbackratingstar == null ? null : feedbackratingstar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.iDVerified
     *
     * @return the value of trding_order_seller.iDVerified
     *
     * @mbggenerated
     */
    public String getIdverified() {
        return idverified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.iDVerified
     *
     * @param idverified the value for trding_order_seller.iDVerified
     *
     * @mbggenerated
     */
    public void setIdverified(String idverified) {
        this.idverified = idverified == null ? null : idverified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.eBayGoodStanding
     *
     * @return the value of trding_order_seller.eBayGoodStanding
     *
     * @mbggenerated
     */
    public String getEbaygoodstanding() {
        return ebaygoodstanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.eBayGoodStanding
     *
     * @param ebaygoodstanding the value for trding_order_seller.eBayGoodStanding
     *
     * @mbggenerated
     */
    public void setEbaygoodstanding(String ebaygoodstanding) {
        this.ebaygoodstanding = ebaygoodstanding == null ? null : ebaygoodstanding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.newUser
     *
     * @return the value of trding_order_seller.newUser
     *
     * @mbggenerated
     */
    public String getNewuser() {
        return newuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.newUser
     *
     * @param newuser the value for trding_order_seller.newUser
     *
     * @mbggenerated
     */
    public void setNewuser(String newuser) {
        this.newuser = newuser == null ? null : newuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.registrationDate
     *
     * @return the value of trding_order_seller.registrationDate
     *
     * @mbggenerated
     */
    public Date getRegistrationdate() {
        return registrationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.registrationDate
     *
     * @param registrationdate the value for trding_order_seller.registrationDate
     *
     * @mbggenerated
     */
    public void setRegistrationdate(Date registrationdate) {
        this.registrationdate = registrationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.site
     *
     * @return the value of trding_order_seller.site
     *
     * @mbggenerated
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.site
     *
     * @param site the value for trding_order_seller.site
     *
     * @mbggenerated
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.status
     *
     * @return the value of trding_order_seller.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.status
     *
     * @param status the value for trding_order_seller.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.userID
     *
     * @return the value of trding_order_seller.userID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.userID
     *
     * @param userid the value for trding_order_seller.userID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.userIDChanged
     *
     * @return the value of trding_order_seller.userIDChanged
     *
     * @mbggenerated
     */
    public String getUseridchanged() {
        return useridchanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.userIDChanged
     *
     * @param useridchanged the value for trding_order_seller.userIDChanged
     *
     * @mbggenerated
     */
    public void setUseridchanged(String useridchanged) {
        this.useridchanged = useridchanged == null ? null : useridchanged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.userIDLastChanged
     *
     * @return the value of trding_order_seller.userIDLastChanged
     *
     * @mbggenerated
     */
    public Date getUseridlastchanged() {
        return useridlastchanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.userIDLastChanged
     *
     * @param useridlastchanged the value for trding_order_seller.userIDLastChanged
     *
     * @mbggenerated
     */
    public void setUseridlastchanged(Date useridlastchanged) {
        this.useridlastchanged = useridlastchanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.vATStatus
     *
     * @return the value of trding_order_seller.vATStatus
     *
     * @mbggenerated
     */
    public String getVatstatus() {
        return vatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.vATStatus
     *
     * @param vatstatus the value for trding_order_seller.vATStatus
     *
     * @mbggenerated
     */
    public void setVatstatus(String vatstatus) {
        this.vatstatus = vatstatus == null ? null : vatstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.sellerInfo_id
     *
     * @return the value of trding_order_seller.sellerInfo_id
     *
     * @mbggenerated
     */
    public Long getSellerinfoId() {
        return sellerinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.sellerInfo_id
     *
     * @param sellerinfoId the value for trding_order_seller.sellerInfo_id
     *
     * @mbggenerated
     */
    public void setSellerinfoId(Long sellerinfoId) {
        this.sellerinfoId = sellerinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.motorsDealer
     *
     * @return the value of trding_order_seller.motorsDealer
     *
     * @mbggenerated
     */
    public String getMotorsdealer() {
        return motorsdealer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.motorsDealer
     *
     * @param motorsdealer the value for trding_order_seller.motorsDealer
     *
     * @mbggenerated
     */
    public void setMotorsdealer(String motorsdealer) {
        this.motorsdealer = motorsdealer == null ? null : motorsdealer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.eBayUnilateralEmail
     *
     * @return the value of trding_order_seller.eBayUnilateralEmail
     *
     * @mbggenerated
     */
    public String getEbayunilateralemail() {
        return ebayunilateralemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.eBayUnilateralEmail
     *
     * @param ebayunilateralemail the value for trding_order_seller.eBayUnilateralEmail
     *
     * @mbggenerated
     */
    public void setEbayunilateralemail(String ebayunilateralemail) {
        this.ebayunilateralemail = ebayunilateralemail == null ? null : ebayunilateralemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.create_user
     *
     * @return the value of trding_order_seller.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.create_user
     *
     * @param createUser the value for trding_order_seller.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.create_time
     *
     * @return the value of trding_order_seller.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.create_time
     *
     * @param createTime the value for trding_order_seller.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trding_order_seller.uuid
     *
     * @return the value of trding_order_seller.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trding_order_seller.uuid
     *
     * @param uuid the value for trding_order_seller.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }
}