package com.base.database.inventory.mapper;

import com.base.database.inventory.model.TaskSyncInventory;
import com.base.database.inventory.model.TaskSyncInventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskSyncInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int countByExample(TaskSyncInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int deleteByExample(TaskSyncInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int insert(TaskSyncInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int insertSelective(TaskSyncInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    List<TaskSyncInventory> selectByExample(TaskSyncInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    TaskSyncInventory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskSyncInventory record, @Param("example") TaskSyncInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskSyncInventory record, @Param("example") TaskSyncInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskSyncInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_sync_inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskSyncInventory record);
}